# Generated by Django 5.1.3 on 2024-11-26 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0002_alter_teacher_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacherexperiences',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacherqualification',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='teacherskill',
            old_name='user_id',
            new_name='user',
        ),
    ]
