# Generated by Django 5.1.3 on 2024-11-28 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0004_alter_tokenproxy_options'),
        ('teacherhire', '0006_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiringToken',
            fields=[
                ('token_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='authtoken.token')),
                ('expires_at', models.DateTimeField()),
            ],
            bases=('authtoken.token',),
        ),
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
