# Generated by Django 5.1.3 on 2024-11-28 17:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0007_expiringtoken_delete_refreshtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='expiringtoken',
            name='refresh_token',
            field=models.CharField(default=uuid.UUID('4cc5afe8-eb19-4ca5-9b2f-9e21a8ee47a8'), max_length=255, unique=True),
        ),
    ]
