# Generated by Django 5.1.3 on 2024-11-29 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0009_refreshtoken_delete_expiringtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RefreshToken',
        ),
    ]
