# Generated by Django 5.1.3 on 2024-11-29 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0010_delete_refreshtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('options', models.JSONField()),
                ('correct_options', models.PositiveBigIntegerField()),
                ('explanations', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherhire.level')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacherhire.subject')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
