# Generated by Django 5.1.3 on 2024-11-30 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0011_level_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanations',
            new_name='option',
        ),
    ]
