# Generated by Django 5.1.3 on 2024-11-30 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0011_level_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explanations',
            new_name='option',
        ),
        migrations.AlterField(
            model_name='classcategory',
            name='name',
            field=models.CharField(blank=True, choices=[('Nursery to U.K.G', 'Nursery to U.K.G'), ('1 to 5', '1 to 5'), ('6 to 8', '6 to 8'), ('9 to 10', '9 to 10'), ('10 to 12', '10 to 12')], max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='educationalqualification',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subject_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='aadhar_no',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='class_categories',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherhire.classcategory'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='fullname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='gender',
            field=models.CharField(blank=True, choices=[('Female', 'Female'), ('Male', 'Male'), ('other', 'other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Indian', 'Indian'), ('other', 'other')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teacherexperiences',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherexperiences',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teacherexperiences',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacherqualification',
            name='institution',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='teacherqualification',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teacherhire.educationalqualification'),
        ),
        migrations.AlterField(
            model_name='teacherqualification',
            name='year_of_passing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='address_type',
            field=models.CharField(blank=True, choices=[('current', 'Current'), ('permanent', 'Permanent')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='block',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='division',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='state',
            field=models.CharField(blank=True, default='Bihar', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='teachersaddress',
            name='village',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
