# Generated by Django 5.1.3 on 2024-11-30 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacherhire', '0012_rename_explanations_question_option'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='option',
        ),
    ]
